travis:
  secure:
    BINSTAR_TOKEN: BjZ+XZDWJp8CCJzvQkmXCrr3A6VbR8zC+W5wdzs+uRw2FcdgCDbXDeOo6Hov1gSxHjdVlWCKgQd9kJXFoGuIohetBuWMSJwDMXHYS7SDDbZA2dCqFCHATm+l5uiEQcDcvJ8R8cX6UThfs0ygCXPPXYzDORgcoR9kpUarYaQ0VtfGfa5Zah/Xfl6q7oGpyCi9RyTdbrcTfsbnr9jaaW3WzjGoTNWROQY2gQaog+vm+VOmNiKxKY7VTOOnX1wFjGbimR4o1VX3+QUAH4aEyeLExdClto5EFfNj+FG58IDZClJMsLJpDX/UAsZt0KFCkYxfAcOiODY3EObT93kycDLR6eOegE7VINQG73PqFZVYY1v9YAH2GvTzVC5/rbbQT1Jmrg5mnXWmfzxPbjWdivGhD4hEMxjhKnQfEl6bnaZKV0wCDkLaKdT4yrQtUGRqPUzTS52dVpb/GQYpUGyjsXhY/mLGBfmQmuFh2nvJigFeayaQf3THyvONYi844kCe7STRzNXg5FQw8QThsl0NbRrlePMSHNh80shLxPFF/VI0NoEukKjk6mHo7Eiz0d4rBDZ8Vs4VblznXN+w5s3CYZ7D+fZMwF1IT2bHpIO0sPGjuYqD7+ZvnClfgRhQN1TRHzUQGFaS0oPh/69um7yseBxoZ6Z0d5eI77OzskKdOTBSQ8I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
